# Sentiment Analysis:

## Bibliotecas Necessárias:

In [38]:
import pandas as pd

## pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer 

## Separa os dados para treinamento e teste
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

## Inicialização dos dados

In [4]:
df = pd.read_csv("./dataset_avaliacoes.csv")

In [8]:
df.head()

,ID_avaliacao,avaliacao,nota,sentimento
0,81841,"Esse smartphone superou minhas expectativas, r...",5,positivo
1,28031,o cheiro e muito desagradavel!! pra quem se in...,2,negativo
2,91332,"Eu fiz a compra a loja não entregou o produto,...",1,negativo
3,110045,"Atendeu minhas expectativas, só achei a luz ru...",4,positivo
4,36929,"Gostei muito, só achei que ficou a desejar a q...",5,positivo

In [9]:
df.shape

(15501, 4)

In [10]:
df.value_counts('sentimento')

sentimento
positivo    7890
negativo    7611
dtype: int64

* Exemplo de avaliações:

In [11]:
print("AVALIAÇÃO POSITIVA")

df.avaliacao[0]

POSITIVA

'Esse smartphone superou minhas expectativas, recomendo'

In [12]:
print("AVALIAÇÃO  NEGATIVA")

df.avaliacao[1]

NEGATIVA

'o cheiro e muito desagradavel!! pra quem se incomoda  nao recomendoo..'

## Transformando textos em dados numéricos:

* Bag Of Words (EXEMPLO DE USO):

In [25]:
texto = ['Comprei um produto ótimo', 'Comprei um produto ruim']

vetorizar = CountVectorizer()

bag = vetorizar.fit_transform(texto)

In [34]:
bag

<2x5 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [27]:
matriz_esparsa = pd.DataFrame.sparse.from_spmatrix(bag, columns=vetorizar.get_feature_names_out())

In [20]:
matriz_esparsa

   comprei  produto  ruim  um  ótimo
0        1        1     0   1      1
1        1        1     1   1      0

* Bag Of Words (APLICAÇÃO):

In [30]:
# max_features: Pega as palavras com as maiores frequências no dataset para montar a matriz esparsa
vectorizer = CountVectorizer(lowercase=False, max_features=50)

bag_of_words = vectorizer.fit_transform(df.avaliacao)

print(bag_of_words.shape)

(15501, 50)

In [33]:
matriz_esparsa_avaliacoes = pd.DataFrame.sparse.from_spmatrix(bag_of_words, columns=vectorizer.get_feature_names_out())

matriz_esparsa_avaliacoes

,Não,Produto,ainda,antes,as,até,bem,bom,chegou,com,...,qualidade,que,recebi,recomendo,se,sem,tem,um,uma,veio
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15497,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
15498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15499,0,1,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Separando os dados em conjunto de treino e teste:

In [54]:
X_treino, X_teste, y_treino, y_teste = train_test_split(bag_of_words, df.sentimento, random_state=4978)

In [58]:
# Usando regressão logística
regressao_logistica = LogisticRegression()

regressao_logistica.fit(X_treino, y_treino)

acuracia = regressao_logistica.score(X_teste, y_teste)

print(acuracia)

0.7979876160990712

In [59]:
def classificar_texto(texto, coluna_texto, coluna_classificacao):
    vetorizar = CountVectorizer(lowercase=False, max_features=50)
    bag_of_words = vetorizar.fit_transform(texto[coluna_texto])
    X_treino, X_teste, y_treino, y_teste = train_test_split(bag_of_words, texto[coluna_classificacao], random_state=4978)
    regressao_logistica = LogisticRegression()
    regressao_logistica.fit(X_treino, y_treino)
    acuracia = regressao_logistica.score(X_teste, y_teste)
    return print(f"Acurácia do modelo com '{coluna_texto}': {acuracia * 100:.2f}%")

In [60]:
classificar_texto(df, 'avaliacao', 'sentimento')

Acurácia do modelo com 'avaliacao': 79.80%